Basics of NumPy Arrays

NumPy stands for Numerical Python and is used for handling large, multi-dimensional arrays and matrices. Unlike Python's built-in lists NumPy arrays provide efficient storage and faster processing for numerical and scientific computations. It offers functions for linear algebra and random number generation making it important for data science and machine learning.

Types of Array:
1. One Dimensional Array
A one-dimensional array is a type of linear array.
2. Multi-Dimensional Array
A Multi-Dimensional Array is an array that can store data in more than one dimension such as rows and columns. In simple terms it is a array of arrays.

ONE DIMENTIONAL ARRAY EXAMPLE

In [5]:
import numpy as np 
a = [1,2,3,4]
arr = np.array(a)
print("list in python:",a)
print("numpy array in python:",arr)

list in python: [1, 2, 3, 4]
numpy array in python: [1 2 3 4]


In [7]:
print(type(a))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


MULTI-DIMENSIONAL ARRAY EXAMPLE

In [10]:
import numpy as np
list_1 = [1,2,3,4]
list_2 = [5,6,7,8]
list_3 = [9,10,11,12]
sample_array = np.array([list_1,list_2,list_3])
print("numpy multi dimentional array in python \n",sample_array)

numpy multi dimentional array in python 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
